# Generated by Django 4.0.4 on 2022-05-26 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('photo', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('clas', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='nature', to='auctions.category')),
            ],
        ),
    ]
